export const sample_foods = [
  {
    id: "1",
    name: "Gurmanski menu",
    cookTime: "10-20 min",
    price: 16.5,
    favorite: false,
    ingredients: ["Pljeskavica u somunu, Coca-Cola, Pommes, luk, kajmak"],
    stars: 4.5,
    imageUrl: "food-1.jpg",
    tags: ["Gotovi menu"],
  },
  {
    id: "2",
    name: "Sarajevski menu",
    price: 14.5,
    cookTime: "20-30 min",
    favorite: true,
    ingredients: ["italy"],
    stars: 5,
    imageUrl: "food-2.jpg",
    tags: ["Gotovi menu"],
  },
  {
    id: "3",
    name: "Banjalučki menu",
    price: 14.5,
    cookTime: "10-15 min",
    favorite: false,
    ingredients: ["italy"],
    stars: 3.5,
    imageUrl: "food-3.jpg",
    tags: ["Gotovi menu"],
  },
  {
    id: "4",
    name: "Pileći batak menu",
    price: 14.0,
    cookTime: "15-20 min",
    favorite: true,
    ingredients: ["italy"],
    stars: 3,
    imageUrl: "food-4.jpg",
    tags: ["Gotovi menu"],
  },
  {
    id: "5",
    name: "Pileća krilca menu",
    price: 14.0,
    cookTime: "40-50 min",
    favorite: false,
    ingredients: ["italy"],
    stars: 3.5,
    imageUrl: "food-5.jpg",
    tags: ["Gotovi menu"],
  },
  {
    id: "6",
    name: "Plata za dvoje",
    price: 42.0,
    cookTime: "40-50 min",
    favorite: false,
    ingredients: ["italy"],
    stars: 4.0,
    imageUrl: "food-6.jpg",
    tags: ["Plate"],
  },
];

// svaki item je objekt sa imenom i brojem artikala!
export const sample_tags = [
  { name: "Sve", count: 6 },
  { name: "Gotovi menu", count: 5 },
  { name: "Plate", count: 1 },
  { name: "Junetina", count: 0 },
  { name: "Junetina sa svinjetinom", count: 0 },
  { name: "Svinjetina", count: 0 },
  { name: "Piletina i pohano", count: 0 },
  { name: "Za djecu", count: 0 },
  { name: "Salate", count: 0 },
  { name: "Deserti", count: 0 },
  { name: "Prilozi i dodaci", count: 0 },
];
